In [13]:
import numpy as np
import pandas as pd
import re
import random

import torch
from tqdm.notebook import tqdm

import pandas as pd
import pathlib
from pathlib import Path

if torch.cuda.is_available():    
    device = torch.device("cuda")
    print('There are %d GPU(s) available.' % torch.cuda.device_count())
    print('Are you feeling lucky today?')
    print('ðŸŽ²...ðŸŽ²...ðŸŽ²...')
    print('You got a GPU:', torch.cuda.get_device_name(0))
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
Are you feeling lucky today?
ðŸŽ²...ðŸŽ²...ðŸŽ²...
You got a GPU: Tesla V100-SXM2-16GB

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#

2021-03-01_low.csv
2021-04-01_low.csv
2021-05-01_low.csv

In [ ]:
#df_03_01 = pd.read_csv('/content/hahaton/2021-03-01_low.csv')

In [14]:
df_04_01 = pd.read_csv('/content/drive/MyDrive/2021-04-01_low.csv', parse_dates=['ts'])

In [ ]:
#df_duration = pd.read_csv('/content/drive/MyDrive/duraion_2021-04-01_low.csv', parse_dates=['ts'])

In [ ]:
#df_duration.sample(10)

In [ ]:
#df_05_01 = pd.read_csv('/content/hahaton/2021-05-01_low.csv')

In [ ]:
#df_03_01.shape

(56247105, 5)

In [4]:
df_04_01.shape

(63157755, 5)

In [ ]:
#df['ap_mac'].nunique() 1811

1811

In [ ]:
# df_04_01['ap_mac'].nunique() 1807

1807

In [ ]:
#df['user_id'].nunique() 33703

33703

In [ ]:
#df_04_01['user_id'].nunique() 34019

34019

In [ ]:
#df['device_id'].nunique() 751646

751646

In [ ]:
#df_1['device_id'].nunique() 794761

794761

In [ ]:
#df['gps'].nunique() 1479

1479

In [ ]:
#df_04_01['gps'].nunique() 1477

1477

In [ ]:
#df_04_01.sample(20) #yyyymmdd hhmmss

                                 ts  ...                                      gps
47321149  2021-04-15 03:34:34+00:00  ...  (55.727012634277344, 37.63620376586914)
7724256   2021-04-04 09:46:32+00:00  ...   (55.72112274169922, 37.60065841674805)
17541580  2021-04-04 06:11:33+00:00  ...  (55.746192932128906, 37.56319808959961)
12936924  2021-04-21 15:44:00+00:00  ...    (55.7493782043457, 37.56379318237305)
31933195  2021-04-22 05:46:32+00:00  ...    (55.7199592590332, 37.66304397583008)
58130471  2021-04-03 09:23:01+00:00  ...   (55.74443054199219, 37.58396530151367)
30347597  2021-04-12 06:35:41+00:00  ...   (55.75262451171875, 37.61231231689453)
8097794   2021-04-18 12:40:05+00:00  ...   (55.73828887939453, 37.58601379394531)
51391658  2021-04-30 20:06:10+00:00  ...   (55.72357177734375, 37.69279861450195)
50219862  2021-04-26 05:11:27+00:00  ...  (55.73225021362305, 37.671485900878906)
47276805  2021-04-27 08:21:07+00:00  ...   (55.71829605102539, 37.59541320800781)
38394694  2021-04-11 07:19:52+00:00  ...   (55.72800827026367, 37.65378952026367)
27349553  2021-04-20 10:55:30+00:00  ...   (55.74991226196289, 37.58246612548828)
52722810  2021-04-12 10:34:19+00:00  ...  (55.747676849365234, 37.59743118286133)
32077173  2021-04-15 17:18:31+00:00  ...   (55.75005340576172, 37.62479782104492)
7368173   2021-04-14 08:41:04+00:00  ...  (55.70783615112305, 37.589229583740234)
59480802  2021-04-26 07:29:04+00:00  ...  (55.74541091918945, 37.656009674072266)
43434655  2021-04-06 02:04:26+00:00  ...    (55.72843933105469, 37.5635986328125)
38673930  2021-04-21 06:01:01+00:00  ...  (55.74700927734375, 37.641380310058594)
17479605  2021-04-04 12:25:42+00:00  ...   (55.75101852416992, 37.59014129638672)

[20 rows x 5 columns]

In [3]:
data_drop = df_04_01.drop(["user_id","ap_mac"], axis=1)

In [6]:
data_drop.columns

Index(['ts', 'device_id', 'gps'], dtype='object')

In [2]:
df_cr = data_drop.sample(15000000)
len(df_cr)

NameError: ignored

In [8]:
df_crop.to_csv('submission_10000.csv', index=False)

In [28]:
df_cr = pd.read_csv('/content/submission_10000.csv', parse_dates=['ts'])

In [45]:
df_cr.set_index(pd.to_datetime(df_cr['ts']))

In [1]:
df_cr.reset_index(inplace=True, drop=True)

NameError: ignored

In [38]:
df_cr['ts'] = df_cr['ts'].round('H')
df_cr['ts'].head(10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

0   2021-04-03 12:00:00+00:00
1   2021-04-03 12:00:00+00:00
2   2021-04-03 12:00:00+00:00
3   2021-04-03 12:00:00+00:00
4   2021-04-03 12:00:00+00:00
5   2021-04-03 12:00:00+00:00
6   2021-04-03 12:00:00+00:00
7   2021-04-03 12:00:00+00:00
8   2021-04-03 12:00:00+00:00
9   2021-04-03 12:00:00+00:00
Name: ts, dtype: datetime64[ns, UTC]

In [7]:
#pd.set_option('display.max_rows', None)

In [39]:
df_cr.head(10)

                         ts  ...                                      gps
0 2021-04-03 12:00:00+00:00  ...    (55.73100280761719, 37.6336669921875)
1 2021-04-03 12:00:00+00:00  ...  (55.74755096435547, 37.595062255859375)
2 2021-04-03 12:00:00+00:00  ...  (55.728275299072266, 37.62435531616211)
3 2021-04-03 12:00:00+00:00  ...  (55.747676849365234, 37.59743118286133)
4 2021-04-03 12:00:00+00:00  ...   (55.72984313964844, 37.59235382080078)
5 2021-04-03 12:00:00+00:00  ...  (55.737823486328125, 37.62553405761719)
6 2021-04-03 12:00:00+00:00  ...   (55.72039031982422, 37.57209396362305)
7 2021-04-03 12:00:00+00:00  ...  (55.73089599609375, 37.609928131103516)
8 2021-04-03 12:00:00+00:00  ...   (55.72984313964844, 37.59235382080078)
9 2021-04-03 12:00:00+00:00  ...  (55.737823486328125, 37.62553405761719)

[10 rows x 3 columns]

In [40]:
#gkk = df_cr.groupby('ts')['gps'].value_counts()
#gkk_df = pd.DataFrame(gkk)
gkk = df_cr.groupby('ts')['gps'].value_counts().sort_values(ascending=True).groupby(level=0).tail(10)
gkk_df = pd.DataFrame(gkk)

In [41]:
gkk_df.head()

                                                                   gps
ts                        gps
2021-04-09 05:00:00+00:00 (55.73060607910156, 37.629512786865234)    4
                          (55.73129653930664, 37.665287017822266)    4
                          (55.74022674560547, 37.58976364135742)     4
                          (55.74799346923828, 37.6812858581543)      4
                          (55.753028869628906, 37.64451599121094)    4

In [42]:
#gkk_df[gkk_df['gps'] == gkk_df.groupby(level=[0])['gps'].transform(max)]
gkk_df[gkk_df['gps'] == gkk_df.groupby(level=[0])['gps'].transform(max)]

                                                                    gps
ts                        gps
2021-04-09 05:00:00+00:00 (55.73086929321289, 37.63642501831055)      6
                          (55.7320442199707, 37.63547897338867)       6
2021-04-11 12:00:00+00:00 (55.735225677490234, 37.59394454956055)     9
2021-04-23 10:00:00+00:00 (55.746116638183594, 37.62641906738281)    24
2021-04-22 10:00:00+00:00 (55.71155548095703, 37.665283203125)       45
2021-04-23 11:00:00+00:00 (55.75302505493164, 37.600711822509766)   106
2021-04-09 06:00:00+00:00 (55.710453033447266, 37.62226867675781)   134
2021-04-22 09:00:00+00:00 (55.74094009399414, 37.63595199584961)    153
2021-04-03 12:00:00+00:00 (55.711326599121094, 37.605369567871094)  262
2021-04-03 13:00:00+00:00 (55.711326599121094, 37.605369567871094)  342

In [ ]:
#gkk_df[gkk_df['gps'] == gkk_df.groupby(level=[0])['gps'].transform(max)]

In [ ]:
#gkk = df_cr.groupby(['gps','ts']).size().reset_index().groupby('ts')[[0]].max()
#gkk

In [ ]:
#gkk = df_cr.groupby(['gps'])['ts'].size().groupby(level=0).max()
#gkk

In [111]:
(df_cr.groupby(['ts', 'gps']).size() 
   .sort_values(ascending=False) 
   .reset_index(name='count') 
   .drop_duplicates(subset='gps'))

                             ts  ... count
0     2021-04-01 01:00:00+00:00  ...   375
1     2021-04-03 13:00:00+00:00  ...   342
3     2021-04-03 13:00:00+00:00  ...   285
5     2021-04-03 13:00:00+00:00  ...   237
6     2021-04-03 13:00:00+00:00  ...   224
8     2021-04-03 13:00:00+00:00  ...   196
10    2021-04-03 13:00:00+00:00  ...   188
12    2021-04-03 13:00:00+00:00  ...   175
13    2021-04-03 13:00:00+00:00  ...   174
14    2021-04-09 06:00:00+00:00  ...   174
15    2021-04-03 13:00:00+00:00  ...   170
17    2021-04-03 13:00:00+00:00  ...   167
19    2021-04-03 13:00:00+00:00  ...   163
21    2021-04-12 15:00:00+00:00  ...   156
26    2021-04-03 13:00:00+00:00  ...   152
28    2021-04-03 13:00:00+00:00  ...   150
30    2021-04-03 13:00:00+00:00  ...   148
31    2021-04-03 13:00:00+00:00  ...   148
32    2021-04-03 13:00:00+00:00  ...   145
33    2021-04-23 11:00:00+00:00  ...   145
34    2021-04-03 13:00:00+00:00  ...   144
35    2021-04-26 09:00:00+00:00  ...   144
36    2021-04-03 13:00:00+00:00  ...   143
37    2021-04-11 12:00:00+00:00  ...   143
39    2021-04-03 13:00:00+00:00  ...   139
40    2021-04-22 10:00:00+00:00  ...   137
42    2021-04-03 13:00:00+00:00  ...   135
44    2021-04-11 12:00:00+00:00  ...   133
49    2021-04-03 12:00:00+00:00  ...   128
50    2021-04-03 13:00:00+00:00  ...   127
52    2021-04-03 13:00:00+00:00  ...   127
54    2021-04-03 13:00:00+00:00  ...   124
58    2021-04-12 15:00:00+00:00  ...   123
59    2021-04-22 10:00:00+00:00  ...   122
62    2021-04-01 01:00:00+00:00  ...   120
66    2021-04-01 01:00:00+00:00  ...   118
67    2021-04-03 12:00:00+00:00  ...   116
68    2021-04-03 13:00:00+00:00  ...   116
69    2021-04-03 13:00:00+00:00  ...   116
71    2021-04-03 13:00:00+00:00  ...   114
73    2021-04-22 10:00:00+00:00  ...   113
74    2021-04-03 13:00:00+00:00  ...   113
75    2021-04-01 01:00:00+00:00  ...   113
76    2021-04-01 01:00:00+00:00  ...   112
79    2021-04-03 12:00:00+00:00  ...   112
82    2021-04-03 13:00:00+00:00  ...   112
84    2021-04-23 11:00:00+00:00  ...   111
89    2021-04-03 13:00:00+00:00  ...   108
90    2021-04-03 13:00:00+00:00  ...   108
93    2021-04-09 06:00:00+00:00  ...   107
101   2021-04-03 13:00:00+00:00  ...   106
102   2021-04-22 10:00:00+00:00  ...   105
103   2021-04-03 13:00:00+00:00  ...   105
104   2021-04-03 13:00:00+00:00  ...   104
106   2021-04-03 13:00:00+00:00  ...   104
108   2021-04-03 13:00:00+00:00  ...   104
109   2021-04-03 13:00:00+00:00  ...   103
111   2021-04-09 06:00:00+00:00  ...   103
112   2021-04-03 13:00:00+00:00  ...   102
113   2021-04-03 13:00:00+00:00  ...   102
115   2021-04-03 13:00:00+00:00  ...   102
116   2021-04-23 11:00:00+00:00  ...   101
117   2021-04-03 13:00:00+00:00  ...   101
121   2021-04-03 13:00:00+00:00  ...   100
124   2021-04-09 06:00:00+00:00  ...    98
125   2021-04-01 01:00:00+00:00  ...    98
127   2021-04-22 10:00:00+00:00  ...    97
128   2021-04-06 09:00:00+00:00  ...    97
129   2021-04-23 11:00:00+00:00  ...    97
132   2021-04-03 13:00:00+00:00  ...    96
133   2021-04-23 11:00:00+00:00  ...    96
136   2021-04-03 13:00:00+00:00  ...    96
137   2021-04-09 06:00:00+00:00  ...    96
139   2021-04-03 12:00:00+00:00  ...    95
147   2021-04-09 06:00:00+00:00  ...    94
149   2021-04-09 06:00:00+00:00  ...    94
150   2021-04-09 06:00:00+00:00  ...    94
152   2021-04-11 12:00:00+00:00  ...    94
155   2021-04-23 11:00:00+00:00  ...    93
156   2021-04-03 13:00:00+00:00  ...    93
161   2021-04-22 10:00:00+00:00  ...    92
166   2021-04-03 12:00:00+00:00  ...    92
168   2021-04-22 10:00:00+00:00  ...    91
169   2021-04-22 10:00:00+00:00  ...    91
173   2021-04-03 12:00:00+00:00  ...    91
174   2021-04-03 13:00:00+00:00  ...    91
180   2021-04-03 12:00:00+00:00  ...    90
181   2021-04-11 11:00:00+00:00  ...    90
182   2021-04-03 13:00:00+00:00  ...    90
184   2021-04-03 13:00:00+00:00  ...    90
186   2021-04-23 11:00:00+00:00  ...    90
192   2021-04-09 06:00:00+00:00  ...    88
196   2021-04-11 12:00:00+00:00  ...    88
198   2021-04-01 01:00:00+00:00  ...    88
201   2021-04-09 06:00:00+00:00  ...    87
202   2021-04-09 06:00:00+00:00  ...    87
207   2021-04-03 13:00:00+00:00  ...    86
209   2021-04-03 13:00:00+00:00  ...    86
210   2021-04-03 13:00:00+00:00  ...    86
211   2021-04-03 13:00:00+00:00  ...    86
214   2021-04-11 12:00:00+00:00  ...    85
218   2021-04-03 13:00:00+00:00  ...    85
219   2021-04-03 13:00:00+00:00  ...    85
221   2021-04-03 12:00:00+00:00  ...    85
223   2021-04-09 06:00:00+00:00  ...    84
227   2021-04-03 13:00:00+00:00  ...    84
228   2021-04-03 13:00:00+00:00  ...    84
229   2021-04-09 06:00:00+00:00  ...    84
232   2021-04-03 13:00:00+00:00  ...    83
233   2021-04-03 13:00:00+00:00  ...    83
235   2021-04-09 06:00:00+00:00  ...    83
236   2021-04-03 13:00:00+00:00  ...    83
237   2021-04-09 06:00:00+00:00  ...    83
245   2021-04-23 11:00:00+00:00  ...    82
247   2021-04-09 06:00:00+00:00  ...    81
250   2021-04-22 10:00:00+00:00  ...    81
252   2021-04-01 01:00:00+00:00  ...    81
254   2021-04-03 13:00:00+00:00  ...    81
256   2021-04-03 12:00:00+00:00  ...    81
257   2021-04-03 13:00:00+00:00  ...    81
265   2021-04-13 14:00:00+00:00  ...    80
266   2021-04-23 11:00:00+00:00  ...    80
270   2021-04-03 13:00:00+00:00  ...    79
272   2021-04-22 10:00:00+00:00  ...    79
283   2021-04-22 10:00:00+00:00  ...    78
284   2021-04-09 06:00:00+00:00  ...    78
289   2021-04-23 11:00:00+00:00  ...    78
291   2021-04-05 13:00:00+00:00  ...    77
294   2021-04-09 06:00:00+00:00  ...    77
296   2021-04-09 06:00:00+00:00  ...    77
297   2021-04-22 10:00:00+00:00  ...    77
298   2021-04-11 12:00:00+00:00  ...    77
302   2021-04-23 11:00:00+00:00  ...    76
304   2021-04-22 10:00:00+00:00  ...    76
306   2021-04-03 13:00:00+00:00  ...    76
310   2021-04-23 11:00:00+00:00  ...    76
313   2021-04-03 12:00:00+00:00  ...    76
315   2021-04-03 13:00:00+00:00  ...    75
316   2021-04-01 01:00:00+00:00  ...    75
318   2021-04-03 13:00:00+00:00  ...    75
320   2021-04-03 13:00:00+00:00  ...    75
322   2021-04-03 13:00:00+00:00  ...    75
325   2021-04-23 11:00:00+00:00  ...    75
326   2021-04-26 09:00:00+00:00  ...    75
328   2021-04-03 12:00:00+00:00  ...    75
339   2021-04-03 13:00:00+00:00  ...    74
341   2021-04-03 12:00:00+00:00  ...    74
346   2021-04-03 13:00:00+00:00  ...    74
350   2021-04-09 06:00:00+00:00  ...    73
353   2021-04-23 11:00:00+00:00  ...    73
355   2021-04-09 06:00:00+00:00  ...    73
357   2021-04-12 13:00:00+00:00  ...    72
359   2021-04-09 06:00:00+00:00  ...    72
373   2021-04-03 13:00:00+00:00  ...    71
378   2021-04-03 13:00:00+00:00  ...    71
379   2021-04-03 13:00:00+00:00  ...    71
380   2021-04-22 10:00:00+00:00  ...    71
381   2021-04-05 13:00:00+00:00  ...    71
389   2021-04-23 11:00:00+00:00  ...    70
399   2021-04-13 14:00:00+00:00  ...    70
402   2021-04-03 13:00:00+00:00  ...    70
409   2021-04-03 13:00:00+00:00  ...    69
413   2021-04-23 11:00:00+00:00  ...    69
417   2021-04-03 13:00:00+00:00  ...    69
421   2021-04-03 13:00:00+00:00  ...    69
423   2021-04-23 11:00:00+00:00  ...    69
424   2021-04-09 06:00:00+00:00  ...    69
425   2021-04-22 10:00:00+00:00  ...    69
428   2021-04-22 10:00:00+00:00  ...    69
430   2021-04-03 12:00:00+00:00  ...    68
433   2021-04-11 12:00:00+00:00  ...    68
434   2021-04-09 06:00:00+00:00  ...    68
439   2021-04-03 13:00:00+00:00  ...    68
443   2021-04-13 14:00:00+00:00  ...    68
449   2021-04-23 11:00:00+00:00  ...    67
451   2021-04-23 11:00:00+00:00  ...    67
457   2021-04-03 12:00:00+00:00  ...    67
461   2021-04-03 13:00:00+00:00  ...    67
466   2021-04-22 10:00:00+00:00  ...    67
467   2021-04-22 10:00:00+00:00  ...    67
469   2021-04-03 13:00:00+00:00  ...    67
470   2021-04-10 09:00:00+00:00  ...    66
473   2021-04-23 11:00:00+00:00  ...    66
476   2021-04-03 13:00:00+00:00  ...    66
477   2021-04-09 06:00:00+00:00  ...    66
479   2021-04-03 13:00:00+00:00  ...    66
481   2021-04-03 13:00:00+00:00  ...    66
485   2021-04-03 13:00:00+00:00  ...    66
489   2021-04-22 10:00:00+00:00  ...    66
496   2021-04-03 13:00:00+00:00  ...    65
499   2021-04-05 13:00:00+00:00  ...    65
501   2021-04-10 09:00:00+00:00  ...    65
504   2021-04-23 11:00:00+00:00  ...    65
506   2021-04-03 13:00:00+00:00  ...    65
509   2021-04-06 09:00:00+00:00  ...    65
510   2021-04-09 06:00:00+00:00  ...    65
511   2021-04-03 13:00:00+00:00  ...    65
514   2021-04-23 11:00:00+00:00  ...    65
519   2021-04-09 06:00:00+00:00  ...    64
521   2021-04-03 12:00:00+00:00  ...    64
522   2021-04-03 13:00:00+00:00  ...    64
534   2021-04-01 01:00:00+00:00  ...    64
537   2021-04-22 14:00:00+00:00  ...    64
541   2021-04-10 09:00:00+00:00  ...    63
544   2021-04-22 10:00:00+00:00  ...    63
550   2021-04-03 13:00:00+00:00  ...    63
551   2021-04-23 11:00:00+00:00  ...    63
558   2021-04-13 14:00:00+00:00  ...    62
562   2021-04-09 06:00:00+00:00  ...    62
565   2021-04-03 12:00:00+00:00  ...    62
567   2021-04-09 06:00:00+00:00  ...    62
569   2021-04-09 06:00:00+00:00  ...    62
574   2021-04-01 01:00:00+00:00  ...    62
576   2021-04-22 10:00:00+00:00  ...    62
581   2021-04-03 13:00:00+00:00  ...    61
582   2021-04-11 12:00:00+00:00  ...    61
585   2021-04-03 13:00:00+00:00  ...    61
586   2021-04-03 13:00:00+00:00  ...    61
591   2021-04-03 13:00:00+00:00  ...    61
592   2021-04-03 13:00:00+00:00  ...    61
594   2021-04-01 01:00:00+00:00  ...    61
597   2021-04-03 13:00:00+00:00  ...    61
601   2021-04-06 09:00:00+00:00  ...    61
603   2021-04-09 06:00:00+00:00  ...    61
619   2021-04-09 06:00:00+00:00  ...    60
621   2021-04-03 13:00:00+00:00  ...    60
626   2021-04-09 06:00:00+00:00  ...    59
628   2021-04-23 11:00:00+00:00  ...    59
629   2021-04-03 13:00:00+00:00  ...    59
632   2021-04-09 06:00:00+00:00  ...    59
633   2021-04-09 03:00:00+00:00  ...    59
637   2021-04-23 11:00:00+00:00  ...    59
638   2021-04-27 12:00:00+00:00  ...    59
639   2021-04-03 13:00:00+00:00  ...    59
644   2021-04-03 12:00:00+00:00  ...    59
648   2021-04-03 13:00:00+00:00  ...    59
658   2021-04-03 13:00:00+00:00  ...    58
662   2021-04-03 13:00:00+00:00  ...    58
663   2021-04-03 13:00:00+00:00  ...    58
665   2021-04-03 13:00:00+00:00  ...    58
668   2021-04-01 01:00:00+00:00  ...    58
669   2021-04-03 13:00:00+00:00  ...    58
670   2021-04-03 13:00:00+00:00  ...    58
671   2021-04-03 13:00:00+00:00  ...    58
673   2021-04-22 10:00:00+00:00  ...    58
677   2021-04-11 12:00:00+00:00  ...    58
679   2021-04-26 09:00:00+00:00  ...    58
680   2021-04-03 13:00:00+00:00  ...    58
684   2021-04-26 09:00:00+00:00  ...    57
686   2021-04-22 10:00:00+00:00  ...    57
687   2021-04-22 10:00:00+00:00  ...    57
689   2021-04-22 10:00:00+00:00  ...    57
691   2021-04-06 09:00:00+00:00  ...    57
694   2021-04-03 13:00:00+00:00  ...    57
697   2021-04-23 11:00:00+00:00  ...    57
700   2021-04-03 13:00:00+00:00  ...    57
701   2021-04-09 06:00:00+00:00  ...    57
714   2021-04-11 11:00:00+00:00  ...    56
718   2021-04-23 11:00:00+00:00  ...    56
720   2021-04-03 13:00:00+00:00  ...    56
727   2021-04-01 01:00:00+00:00  ...    56
729   2021-04-10 09:00:00+00:00  ...    56
737   2021-04-03 12:00:00+00:00  ...    56
739   2021-04-01 01:00:00+00:00  ...    56
741   2021-04-22 10:00:00+00:00  ...    56
744   2021-04-23 11:00:00+00:00  ...    56
750   2021-04-23 11:00:00+00:00  ...    55
754   2021-04-03 12:00:00+00:00  ...    55
756   2021-04-22 10:00:00+00:00  ...    55
758   2021-04-23 11:00:00+00:00  ...    55
762   2021-04-01 01:00:00+00:00  ...    55
766   2021-04-12 15:00:00+00:00  ...    55
777   2021-04-01 01:00:00+00:00  ...    55
781   2021-04-05 13:00:00+00:00  ...    55
782   2021-04-01 01:00:00+00:00  ...    55
783   2021-04-03 13:00:00+00:00  ...    55
785   2021-04-23 11:00:00+00:00  ...    54
793   2021-04-26 09:00:00+00:00  ...    54
803   2021-04-11 11:00:00+00:00  ...    54
808   2021-04-03 12:00:00+00:00  ...    54
818   2021-04-23 11:00:00+00:00  ...    54
819   2021-04-03 13:00:00+00:00  ...    54
820   2021-04-03 12:00:00+00:00  ...    54
824   2021-04-26 09:00:00+00:00  ...    54
836   2021-04-22 10:00:00+00:00  ...    53
844   2021-04-03 13:00:00+00:00  ...    53
847   2021-04-03 13:00:00+00:00  ...    53
851   2021-04-22 10:00:00+00:00  ...    53
854   2021-04-11 12:00:00+00:00  ...    53
855   2021-04-23 11:00:00+00:00  ...    53
856   2021-04-22 10:00:00+00:00  ...    53
857   2021-04-03 13:00:00+00:00  ...    53
863   2021-04-03 13:00:00+00:00  ...    53
869   2021-04-27 20:00:00+00:00  ...    52
874   2021-04-03 13:00:00+00:00  ...    52
881   2021-04-09 06:00:00+00:00  ...    52
886   2021-04-23 11:00:00+00:00  ...    52
888   2021-04-23 11:00:00+00:00  ...    52
894   2021-04-03 13:00:00+00:00  ...    52
895   2021-04-22 10:00:00+00:00  ...    52
901   2021-04-22 10:00:00+00:00  ...    52
906   2021-04-02 14:00:00+00:00  ...    52
912   2021-04-23 11:00:00+00:00  ...    51
919   2021-04-09 06:00:00+00:00  ...    51
921   2021-04-22 10:00:00+00:00  ...    51
926   2021-04-03 13:00:00+00:00  ...    51
927   2021-04-03 13:00:00+00:00  ...    51
929   2021-04-23 11:00:00+00:00  ...    51
940   2021-04-09 06:00:00+00:00  ...    51
941   2021-04-07 12:00:00+00:00  ...    51
955   2021-04-03 13:00:00+00:00  ...    50
956   2021-04-09 06:00:00+00:00  ...    50
958   2021-04-03 13:00:00+00:00  ...    50
970   2021-04-23 11:00:00+00:00  ...    50
980   2021-04-07 12:00:00+00:00  ...    50
998   2021-04-03 13:00:00+00:00  ...    49
1002  2021-04-22 10:00:00+00:00  ...    49
1012  2021-04-22 10:00:00+00:00  ...    49
1017  2021-04-03 13:00:00+00:00  ...    49
1026  2021-04-03 13:00:00+00:00  ...    49
1028  2021-04-09 06:00:00+00:00  ...    49
1032  2021-04-26 09:00:00+00:00  ...    49
1035  2021-04-27 20:00:00+00:00  ...    48
1036  2021-04-09 06:00:00+00:00  ...    48
1041  2021-04-29 07:00:00+00:00  ...    48
1045  2021-04-26 09:00:00+00:00  ...    48
1047  2021-04-01 01:00:00+00:00  ...    48
1050  2021-04-03 13:00:00+00:00  ...    48
1052  2021-04-22 10:00:00+00:00  ...    48
1054  2021-04-23 11:00:00+00:00  ...    48
1061  2021-04-11 12:00:00+00:00  ...    48
1063  2021-04-22 10:00:00+00:00  ...    48
1070  2021-04-23 11:00:00+00:00  ...    48
1078  2021-04-23 16:00:00+00:00  ...    48
1080  2021-04-11 11:00:00+00:00  ...    48
1086  2021-04-09 06:00:00+00:00  ...    47
1091  2021-04-22 10:00:00+00:00  ...    47
1092  2021-04-01 01:00:00+00:00  ...    47
1095  2021-04-09 06:00:00+00:00  ...    47
1096  2021-04-03 12:00:00+00:00  ...    47
1098  2021-04-11 11:00:00+00:00  ...    47
1100  2021-04-03 13:00:00+00:00  ...    47
1106  2021-04-22 10:00:00+00:00  ...    47
1107  2021-04-26 09:00:00+00:00  ...    47
1112  2021-04-03 13:00:00+00:00  ...    47
1124  2021-04-22 10:00:00+00:00  ...    47
1128  2021-04-03 13:00:00+00:00  ...    47
1137  2021-04-03 13:00:00+00:00  ...    47
1143  2021-04-09 06:00:00+00:00  ...    47
1149  2021-04-26 09:00:00+00:00  ...    46
1162  2021-04-12 15:00:00+00:00  ...    46
1172  2021-04-22 10:00:00+00:00  ...    46
1182  2021-04-03 12:00:00+00:00  ...    46
1187  2021-04-09 06:00:00+00:00  ...    46
1198  2021-04-03 12:00:00+00:00  ...    46
1204  2021-04-03 13:00:00+00:00  ...    46
1206  2021-04-03 13:00:00+00:00  ...    45
1212  2021-04-03 13:00:00+00:00  ...    45
1214  2021-04-23 11:00:00+00:00  ...    45
1222  2021-04-09 06:00:00+00:00  ...    45
1223  2021-04-03 13:00:00+00:00  ...    45
1227  2021-04-03 13:00:00+00:00  ...    45
1229  2021-04-23 11:00:00+00:00  ...    45
1231  2021-04-03 13:00:00+00:00  ...    45
1232  2021-04-26 09:00:00+00:00  ...    45
1237  2021-04-03 12:00:00+00:00  ...    45
1241  2021-04-09 06:00:00+00:00  ...    45
1253  2021-04-03 13:00:00+00:00  ...    45
1257  2021-04-09 06:00:00+00:00  ...    45
1267  2021-04-11 11:00:00+00:00  ...    45
1268  2021-04-22 10:00:00+00:00  ...    45
1270  2021-04-22 10:00:00+00:00  ...    45
1272  2021-04-03 12:00:00+00:00  ...    45
1276  2021-04-03 12:00:00+00:00  ...    45
1290  2021-04-23 11:00:00+00:00  ...    44
1295  2021-04-09 06:00:00+00:00  ...    44
1304  2021-04-23 11:00:00+00:00  ...    44
1309  2021-04-09 06:00:00+00:00  ...    44
1320  2021-04-23 11:00:00+00:00  ...    44
1336  2021-04-02 07:00:00+00:00  ...    44
1342  2021-04-22 10:00:00+00:00  ...    44
1344  2021-04-03 13:00:00+00:00  ...    44
1346  2021-04-23 11:00:00+00:00  ...    44
1347  2021-04-03 13:00:00+00:00  ...    44
1351  2021-04-03 13:00:00+00:00  ...    44
1352  2021-04-03 13:00:00+00:00  ...    44
1355  2021-04-23 11:00:00+00:00  ...    44
1361  2021-04-22 10:00:00+00:00  ...    44
1362  2021-04-03 12:00:00+00:00  ...    44
1363  2021-04-22 10:00:00+00:00  ...    44
1366  2021-04-23 11:00:00+00:00  ...    44
1375  2021-04-23 11:00:00+00:00  ...    43
1381  2021-04-01 01:00:00+00:00  ...    43
1385  2021-04-22 10:00:00+00:00  ...    43
1395  2021-04-03 13:00:00+00:00  ...    43
1397  2021-04-09 06:00:00+00:00  ...    43
1404  2021-04-03 13:00:00+00:00  ...    43
1410  2021-04-23 11:00:00+00:00  ...    43
1411  2021-04-23 11:00:00+00:00  ...    43
1412  2021-04-03 12:00:00+00:00  ...    43
1427  2021-04-23 11:00:00+00:00  ...    43
1430  2021-04-11 12:00:00+00:00  ...    43
1431  2021-04-22 10:00:00+00:00  ...    43
1436  2021-04-23 11:00:00+00:00  ...    43
1437  2021-04-22 10:00:00+00:00  ...    43
1440  2021-04-11 12:00:00+00:00  ...    43
1442  2021-04-23 11:00:00+00:00  ...    43
1444  2021-04-23 11:00:00+00:00  ...    42
1446  2021-04-23 11:00:00+00:00  ...    42
1480  2021-04-22 10:00:00+00:00  ...    42
1486  2021-04-03 12:00:00+00:00  ...    42
1489  2021-04-23 11:00:00+00:00  ...    42
1490  2021-04-26 13:00:00+00:00  ...    42
1494  2021-04-03 13:00:00+00:00  ...    42
1503  2021-04-03 13:00:00+00:00  ...    42
1508  2021-04-03 13:00:00+00:00  ...    42
1513  2021-04-06 09:00:00+00:00  ...    42
1521  2021-04-22 10:00:00+00:00  ...    42
1526  2021-04-03 13:00:00+00:00  ...    42
1529  2021-04-23 11:00:00+00:00  ...    42
1535  2021-04-03 13:00:00+00:00  ...    41
1536  2021-04-23 11:00:00+00:00  ...    41
1554  2021-04-26 09:00:00+00:00  ...    41
1563  2021-04-03 12:00:00+00:00  ...    41
1577  2021-04-23 11:00:00+00:00  ...    41
1579  2021-04-11 12:00:00+00:00  ...    41
1580  2021-04-23 11:00:00+00:00  ...    41
1589  2021-04-03 13:00:00+00:00  ...    41
1598  2021-04-03 13:00:00+00:00  ...    41
1605  2021-04-03 13:00:00+00:00  ...    41
1629  2021-04-03 13:00:00+00:00  ...    40
1630  2021-04-01 10:00:00+00:00  ...    40
1635  2021-04-24 17:00:00+00:00  ...    40
1636  2021-04-03 12:00:00+00:00  ...    40
1652  2021-04-27 20:00:00+00:00  ...    40
1659  2021-04-03 12:00:00+00:00  ...    40
1660  2021-04-27 12:00:00+00:00  ...    40
1665  2021-04-03 13:00:00+00:00  ...    40
1674  2021-04-11 12:00:00+00:00  ...    40
1678  2021-04-03 13:00:00+00:00  ...    40
1683  2021-04-23 11:00:00+00:00  ...    40
1692  2021-04-09 06:00:00+00:00  ...    40
1694  2021-04-22 10:00:00+00:00  ...    40
1695  2021-04-23 11:00:00+00:00  ...    40
1696  2021-04-07 14:00:00+00:00  ...    40
1703  2021-04-23 11:00:00+00:00  ...    40
1707  2021-04-22 10:00:00+00:00  ...    39
1709  2021-04-03 13:00:00+00:00  ...    39
1714  2021-04-23 11:00:00+00:00  ...    39
1715  2021-04-23 11:00:00+00:00  ...    39
1716  2021-04-09 03:00:00+00:00  ...    39
1723  2021-04-03 13:00:00+00:00  ...    39
1724  2021-04-23 11:00:00+00:00  ...    39
1725  2021-04-03 13:00:00+00:00  ...    39
1727  2021-04-09 03:00:00+00:00  ...    39
1728  2021-04-22 10:00:00+00:00  ...    39
1743  2021-04-11 12:00:00+00:00  ...    39
1745  2021-04-03 13:00:00+00:00  ...    39
1750  2021-04-03 13:00:00+00:00  ...    39
1752  2021-04-22 10:00:00+00:00  ...    39
1753  2021-04-09 06:00:00+00:00  ...    39
1765  2021-04-22 10:00:00+00:00  ...    39
1767  2021-04-06 09:00:00+00:00  ...    39
1772  2021-04-22 10:00:00+00:00  ...    39

In [64]:
df_gr = pd.DataFrame(df_cr.groupby(["gps", "ts"])["device_id"].value_counts())
df_gr

                                                                                                    device_id
gps                                     ts                        device_id
(55.655155181884766, 37.75764846801758) 2021-04-01 01:00:00+00:00 ba4f6f520f99fcc486e5dcec0be604de          3
                                                                  05798c44b2f4205b5db589dd81c8f26b          2
                                                                  082e63b9da26d01e52dc6cb3764ce9ea          2
                                                                  cdc689f710d24b607153eaf80e0029e1          2
                                        2021-04-01 10:00:00+00:00 ab6f2f942d92eac1841ad58ca4cffb96          2
...                                                                                                       ...
(55.753211975097656, 37.59275436401367) 2021-04-23 11:00:00+00:00 0019e95944aae3379b87e905ac70acc2          2
                                        2021-04-23 16:00:00+00:00 0a2f8cb789d98b488436fce63fe72d62          2
                                        2021-04-24 17:00:00+00:00 04b9804eec94326e1826962a747f9c88          4
                                        2021-04-25 08:00:00+00:00 915bff2a01aee92d2d7610ffabeabadf          2
                                        2021-04-27 13:00:00+00:00 5d6568be81952faff80288e180b6aea6          1

[194720 rows x 1 columns]

In [34]:
df_cr['ts'] = df_cr['ts'].round('H')
df_cr['ts'].head(10)

0   2021-04-03 12:00:00+00:00
1   2021-04-03 12:00:00+00:00
2   2021-04-03 12:00:00+00:00
3   2021-04-03 12:00:00+00:00
4   2021-04-03 12:00:00+00:00
5   2021-04-03 12:00:00+00:00
6   2021-04-03 12:00:00+00:00
7   2021-04-03 12:00:00+00:00
8   2021-04-03 12:00:00+00:00
9   2021-04-03 12:00:00+00:00
Name: ts, dtype: datetime64[ns, UTC]

In [ ]:
#df.reset_index(inplace=True)